### ISSUE TITLE
Include a zip/3 predicate

### ISSUE THREAD

**Issue by eazar001** [mndrix/list_util#12]
Something like this seems entirely natural for zipping two lists into pairs:
```
zip_(Xs, Ys, Zs) :-
  Zip = (\X^Y^Z^ (Z = X-Y)),
  maplist(Zip, Xs, Ys, Zs).
```
However the major limitation here is that both lists are required to be the same size.
So there is this simpler variant:
```
%% zip(?Xs, ?Ys, ?Zs)

zip([], [], []).
zip([], [_|_], []).
zip([_|_], [], []).

zip([X|Xs], [Y|Ys], [X-Y|Zs]) :-
  zip(Xs, Ys, Zs).
```
The only real disadvantage here is that in some modes, some unwanted and infrequently used results (albeit very correct ones) will be returned as solutions. Either way I thought something like the "zip predicate" would be a useful addition to this pack. This seems especially cool in tandem with things like the lazy list. What is your opinion?

**Comment by eazar001** [comment]
I was also considering that one could restrict the modes a little, and perhaps restrict the outputs to closed lists like such:
```
zip(Xs, Ys, Zs) :-
  once(zip_(Xs, Ys, Zs)).

zip_([], [], []).
zip_([], [_|_], []).
zip_([_|_], [], []).

zip_([X|Xs], [Y|Ys], [X-Y|Zs]) :-
  zip_(Xs, Ys, Zs).
```

**Comment by mndrix** [comment]
I didn't implement this predicate because the standard [pairs library](http://www.swi-prolog.org/pldoc/man?section=pairs) has the predicate `pairs_keys_value/3`.  Maybe, `zip/3` should just be an alias to that predicate (shorter name, convenient for those with a functional background).

What do you think?

**Comment by eazar001** [comment]
@mndrix , ahh I didn't know about pairs_keys_values/3. However even that implementation still has one main weakness:
It won't work with this input: 
`pairs_keys_values(Pairs, [1,2,3], [a,b,c,d]).`
Whereas my zip/3 will work with this input. Or perhaps I'm just not grokking how to use the library properly? So i suppose my main gripe, is that list inputs have to be equal to use the standard implementations.

**Comment by eazar001** [comment]
On the other hand, after thinking about what you suggested a little more, perhaps this issue is better addressed to SWI itself. Which may have been what you were initially suggesting, hehe.

**Comment by mndrix** [comment]
> For example, when testing zip in Haskell I get expected behavior:
> 
> Prelude GOA> zip [1..3] ['a'..'d']
> [(1,'a'),(2,'b'),(3,'c')]

In a functional language, Haskell's definition works really well.  In Prolog, that definition leads to infinite choicepoints.  For example, if we have this behavior in Prolog:

```prolog
?- zip(Pairs,[1,2,3],[a,b,c,d]).
Pairs = [1-a,2-b,3-c].
```

then we should also have this behavior

```prolog
?- zip([1-a,2-b,3-c],Keys,Values).
Keys = [1,2,3],
Values = [a,b,c] ;
Keys = [1,2,3],
Values = [a,b,c,_] ;
Keys = [1,2,3],
Values = [a,b,c,_,_] ;
...
```

Namely, there are infinitely many lists for `Keys` and `Values` which satisfy `zip([1-a,2-b,3-c],Keys,Values)`.  In practice, I've found it more useful to have the implicit constraint `same_length(Keys,Values)`, which is implied by the current definition of pairs_keys_values/3.

Does that help @eazar001 ?  Do you have a specific use case where you want `Keys` and `Values` to have different lengths?  That might help.

**Comment by eazar001** [comment]
@mndrix Yes, I more or less understand what you're saying.
To be specific though, in my example usage of my above defined zip/3 I get:
```
zip(Keys, Values, [1-a,2-b,3-c]).
Keys = [1, 2, 3],
Values = [a, b, c] ;
Keys = [1, 2, 3],
Values = [a, b, c, _G1812|_G1813] ;
Keys = [1, 2, 3, _G1812|_G1813],
Values = [a, b, c].
```
... which is a variant of what you described. In this case one solution is [1,2,3] and and [a,b,c]. The other is [1,2,3] and a list that contains a,b,c, and at least one other element. In the final solution, the first list is one that contains 1,2,3, and at least one other element, with the other list being constrained to a finite [a,b,c]. 

If what you're trying to suggest is that I _should_ be displaying infinite choicepoints, then yes that is a weakness in the example implementation I wrote above. Either way, it appears the main take-home message here is that this doesn't seem to be a very practical/idiomatic addition within the framework of prolog.
 

> Does that help @eazar001 ? Do you have a specific use case where you want Keys and Values to have different lengths? That might help.

No, there wasn't any particular use-case that this issue had in mind. I just more or less want to instigate a discussion and reason about why (or why not) this predicate should be included in this pack. Overall, I appreciate all the excellent work you have done with the ecosystem. Thanks for your time @mndrix.
